"""
UserWarning() - Python Built-in Function

Description:
Base class for warnings generated by user code.
"""

# Examples:

# Example usage of UserWarning()
# Add your examples here

result = UserWarning()
print(result)
